services:
  rust-build-env:
    working_dir: /app
    volumes:
      - ./rust-edge-lambda:/app
    build:
      context: rust-edge-lambda
      dockerfile: Dockerfile
    container_name: rust-build-env
    environment:
      - JWT_SECRET
  node-build-env:
    image: node:lts-slim
    working_dir: /app
    volumes:
      - ./rust-edge-lambda:/app/rust-edge-lambda
      - ./node-adapter:/app/node-adapter
    container_name: node-build-env